### ISSUE TITLE
Python installation issue

### ISSUE THREAD

**Issue by dttrugman** [tbenthompson/okada_wrapper#2]
Hi, I'm trying to install the python version on Mac (or Linux - neither has worked for me).

I keep getting a strange error message: 
  Failed building wheel for okada-wrapper
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/xp/b5yg9w6j1qnfhzw22xd_p01m0000gn/T/pip-install-n9outi2d/okada-wrapper/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/xp/b5yg9w6j1qnfhzw22xd_p01m0000gn/T/pip-record-tv__isgf/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xp/b5yg9w6j1qnfhzw22xd_p01m0000gn/T/pip-install-n9outi2d/okada-wrapper/

I'm running Python 3.6.7. Any tips/suggestions? I've attached the full terminal output in case that helps.
[error.txt](https://github.com/tbenthompson/okada_wrapper/files/3337152/error.txt)

**Comment by tbenthompson** [comment]
The main error is the linker error I copied from below. It looks like the issue is that there's some failure in linking to the Python system libraries. `okada_wrapper` uses a numpy package called f2py to wrap the Fortran code and make it callable from Python. Could you try to use f2py to wrap some simple Fortran code and see if you get the same error? This is a useful guide: https://docs.scipy.org/doc/numpy/f2py/getting-started.html#the-quick-way If you do get the same error with simpler Fortran code, you might get better advice by contacting the f2py folks for help. The other thing I see in the error log is `ld: warning: directory not found for option '-L/lib'`. That might be part of the issue with your python library path. 

```
...
      "__Py_NoneStruct", referenced from:
          _f2py_rout_DC3D_dc3d0 in DC3Dmodule.o
          _f2py_rout_DC3D_ua0 in DC3Dmodule.o
          _f2py_rout_DC3D_ub0 in DC3Dmodule.o
          _f2py_rout_DC3D_uc0 in DC3Dmodule.o
          _f2py_rout_DC3D_dc3d in DC3Dmodule.o
          _f2py_rout_DC3D_ua in DC3Dmodule.o
          _f2py_rout_DC3D_ub in DC3Dmodule.o
          ...
      "_main", referenced from:
         implicit entry/start for main executable
    ld: symbol(s) not found for architecture x86_64
    collect2: error: ld returned 1 exit status
```

**Comment by dttrugman** [comment]
Thanks. Using basic f2py gives a very similar error. You may be right about the warning. The strange thing is that there is no /lib on my computer, so I wonder why it is trying to link to it?

**Comment by tbenthompson** [comment]
Huh. Good luck figuring this out! I don't think I'm going to be very useful.

**Comment by rzinke** [comment]
Hello, 
Was this issue ever resolved? I am getting a similar error message with python setup.py install.
Please let me know. I am happy to help troubleshoot.
Rob

**Comment by tbenthompson** [comment]
This was never an issue with `okada_wrapper` but instead an issue with his f2py installation. You may be having similar problems.
